name: Weekly Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * 3"

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run scrape
        run: npx ts-node src/scraper.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
